### ISSUE TITLE
Unable to access Wanikani Dashboard: TypeError found

### ISSUE THREAD

**Issue by Jonathan-Fang** [ranger-ross/nihongo-stats#614]
I inputted my Wanikani v2 API key and it returned the following error message.
![image](https://github.com/ranger-ross/nihongo-stats/assets/76038959/cb49a7e6-012b-4c32-8714-cb0cb7535909)

I have tried force refreshing and making a new API key and the same error returned.
Please advise.

**Comment by ranger-ross** [comment]
Thanks for reporting this issue.

I am reviewing the code and the issue appears to be related to the [level progression](https://docs.api.wanikani.com/20170710/#level-progressions) API.

Unfortunately, I cannot reproduce it with my WK account. 
Can I ask what WK level you are? 
I think if you are level 1, there could possibly be a bug in logic.

Also if you feel comfortable sharing a read-only API key for your WK account, I could also use that to debug. (but no pressure if you would prefer not to do that)

**Comment by Jonathan-Fang** [comment]
Hi Ross,

My WK level is 12.

Sure, here's a read-only API key for my WK account.
9993fc65-fbe4-4a59-b411-27ea150bd7a7

Many thanks,
Jonathan Fang

**Comment by ranger-ross** [comment]
@Jonathan-Fang Thanks for sharing.

I looked into it and found the issue. You account is quite old and it appears that the Wanikani is missing some data for your previous levels. I was able to create a workaround in #615 and deployed it.

I think you should be able to login now, but some data will be missing. 
If you run into more issues feel free to open another issue :smile:
